"use strict";
const { numberToWordsLA, numberToWordsEN } = require("./index");
console.log(numberToWordsLA(0));
console.log(numberToWordsLA(1));
console.log(numberToWordsLA(10));
console.log(numberToWordsLA(11));
console.log(numberToWordsLA(20));
console.log(numberToWordsLA(21));
console.log(numberToWordsLA(50));
console.log(numberToWordsLA(51));
console.log(numberToWordsLA(100));
console.log(numberToWordsLA(101));
console.log(numberToWordsLA(120));
console.log(numberToWordsLA(1000));
console.log(numberToWordsLA(1001));
console.log(numberToWordsLA(1010));
console.log(numberToWordsLA(10000));
console.log(numberToWordsLA(10001));
console.log(numberToWordsLA(10100));
console.log(numberToWordsLA(10101));
console.log(numberToWordsLA(100000));
console.log(numberToWordsLA(100001));
console.log(numberToWordsLA(100100));
console.log(numberToWordsLA(1000000));
console.log(numberToWordsLA(1000001));
console.log(numberToWordsLA(1000100));
//# sourceMappingURL=test.js.map